### ISSUE TITLE
Color preset: Red as a recipe

### ISSUE THREAD

**Issue by montyfabio** [MichaelGreenNZ/MA3_StartShow#1]
hello,
Red color preset starts as a recipe like white cto and ctb.. i guess is an error for Red

**Comment by MichaelGreenNZ** [comment]
I'm not sure I understand? Can you take some photos or a video of the issue?

**Comment by MichaelGreenNZ** [comment]
> error

Oh I think I see the issue. Let me take a look and try to fix that.

**Comment by MichaelGreenNZ** [comment]
Thanks for spotting this, Fixed it and updated showfile.

**Comment by MichaelGreenNZ** [comment]
Thanks for spotting this, Fixed it and updated showfile.
